# Generated by Django 4.2 on 2024-09-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_comment='관리자 이메일', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_comment='관리자 이름', max_length=20)),
                ('addr', models.CharField(db_comment='관리자 주소', max_length=255)),
                ('addr2', models.CharField(db_comment='관리자 상세 주소', max_length=255)),
                ('phone', models.CharField(db_comment='관리자 연락처', max_length=11)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dormant', models.BooleanField(db_comment='휴면계정 여부', default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authority_id', models.CharField(db_comment='권한 ID', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('authority_name', models.CharField(db_comment='권한 이름', max_length=20)),
                ('authority_menu', models.CharField(db_comment='권한 메뉴', max_length=255)),
                ('authority_level_code', models.CharField(db_comment='권한 단계', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityMenu',
            fields=[
                ('authority_menu_code', models.BigAutoField(db_comment='권한 메뉴 ID', primary_key=True, serialize=False, unique=True)),
                ('authority_menu_name', models.CharField(db_comment='권한 메뉴 이름', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(db_comment='고객 ID', primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(db_comment='고객 이름', max_length=20)),
                ('building_type', models.CharField(db_comment='고객 건물 형식', max_length=255)),
                ('client_phone', models.CharField(db_comment='고객 연락처', max_length=11)),
                ('client_email', models.CharField(db_comment='고객 이메일', max_length=40)),
                ('client_addr1', models.CharField(db_comment='고객 주소', max_length=255)),
                ('client_addr2', models.CharField(db_comment='고객 상세 주소', max_length=255)),
                ('client_state', models.CharField(db_comment='?', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('combo_code', models.CharField(db_comment='콤보 코드', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('combo_name', models.CharField(db_comment='콤보 이름', max_length=20)),
                ('combo_title', models.CharField(db_comment='콤보 제목', max_length=20)),
                ('combo_state', models.CharField(db_comment='상태값', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.CharField(db_comment='업체 아이디', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('contractor_name', models.CharField(db_comment='업체명', max_length=20)),
                ('contractor_email', models.CharField(db_comment='업체 이메일', max_length=40)),
                ('contractor_tel', models.CharField(db_comment='업체 전화번호', max_length=11)),
                ('contractor_business_info', models.CharField(db_comment='사업정보', max_length=255)),
                ('contractor_state', models.CharField(db_comment='상태값', max_length=10)),
                ('business_name', models.CharField(db_comment='사업명', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.BigAutoField(db_comment='딜러 ID', primary_key=True, serialize=False, unique=True)),
                ('dealer_name', models.CharField(db_comment='딜러 이름', max_length=20)),
                ('dealer_phone', models.CharField(db_comment='딜러 연락처', max_length=11)),
                ('dealer_branch', models.CharField(db_comment='딜러 지점', max_length=255)),
                ('dealer_loc', models.CharField(db_comment='딜러 지역', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationRequest',
            fields=[
                ('ist_req_contract_num', models.BigAutoField(db_comment='계약 번호', primary_key=True, serialize=False, unique=True)),
                ('reception_num', models.CharField(db_comment='접수 번호', max_length=20)),
                ('ist_req_date', models.DateTimeField(auto_now_add=True, db_comment='접수일')),
                ('ist_req_vehi_num', models.CharField(db_comment='신청 대수', max_length=10)),
                ('ist_req_type', models.CharField(db_comment='구분 (개인, 법인)', max_length=20)),
                ('ist_req_visit_date', models.DateTimeField(db_comment='실사 희망일시')),
                ('ist_req_cancel_msg', models.TextField(db_comment='메세지')),
                ('ist_req_cancel_reason', models.TextField(db_comment='취소 사유')),
                ('ist_req_cancel_date', models.DateTimeField(db_comment='취소 일시')),
                ('ist_req_state', models.CharField(db_comment='진행 상태', max_length=10)),
                ('client_id', models.ForeignKey(db_comment='고객 번호', on_delete=django.db.models.deletion.CASCADE, to='erp_system.client')),
                ('dealer_id', models.ForeignKey(db_comment='딜러 번호', on_delete=django.db.models.deletion.CASCADE, to='erp_system.dealer')),
                ('user_email', models.ForeignKey(db_comment='이메일(담당자)', on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('sqno_num', models.BigAutoField(db_comment='상태변경 ID', primary_key=True, serialize=False, unique=True)),
                ('history_update_name', models.CharField(db_comment='변경자', max_length=20)),
                ('history_update_date', models.DateTimeField(db_comment='변경 일시')),
                ('history_before_state', models.CharField(db_comment='변경 전 상태', max_length=10)),
                ('history_after_state', models.CharField(db_comment='변경 후 상태', max_length=10)),
                ('history_asir', models.CharField(db_comment='설치 AS 구분', max_length=255)),
                ('ist_req_contract_num', models.ForeignKey(db_comment='설치 계약 번호', on_delete=django.db.models.deletion.CASCADE, related_name='his_ist_id', to='erp_system.installationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ASRegister',
            fields=[
                ('as_register_num', models.BigAutoField(db_comment='AS 접수번호', primary_key=True, serialize=False, unique=True)),
                ('as_engineer', models.CharField(db_comment='AS 설치기사', max_length=20)),
                ('as_date', models.DateTimeField(db_comment='AS 방문 희망일')),
                ('as_detail', models.TextField(db_comment='AS 내용')),
                ('as_cancellation', models.TextField(db_comment='AS 취소 사유')),
                ('as_cancellation_date', models.DateTimeField(db_comment='AS 취소일자')),
                ('as_state', models.CharField(db_comment='AS 상태값', max_length=10)),
                ('ist_req_contract_num', models.ForeignKey(db_comment='계약 번호', on_delete=django.db.models.deletion.CASCADE, related_name='as_ist_id', to='erp_system.installationrequest')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Authority_id',
            field=models.ForeignKey(db_comment='관리자 권한', on_delete=django.db.models.deletion.CASCADE, to='erp_system.authority'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
